services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src:ro
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  web:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    restart: unless-stopped
