[project]
name = "ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elevenlabs>=1.57.0",
    "google-genai>=1.11.0",
    "python-dotenv>=1.1.0",
    "wave>=0.0.2",
]
